
[build.environment]
  NPM_FLAGS="--prefix=/"
  NODE_VERSION = "14"

[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"
[[plugins]]
  package = "@netlify/plugin-nextjs"