name: Send someday, i learn cheatsheet at 11:am
on:
  schedule:
    - cron: "0 11 * * *"
jobs:
  someday:
    name: Someday
    runs-on: ubuntu-latest
    steps:
    - uses: JiangWeixian/cheatsheets-sdil-actions@v1
      with:
          CHEATSHEET_HOST: jiangweixian-cheatsheets.vercel.app
          debug: true
      env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
