name: "cheatsheet updater"

on:
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - master
      - 'v*'

jobs:
  # test action works running from the schedule
  updater:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ohmycheatsheet/actions-updater@v1
      with:
        repo: ohmycheatsheet/cheatsheets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}