name: "Cheatsheet updater"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ohmycheatsheet/actions-updater@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
